id: IF089CA46
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T03:59:39+00:00'
last_modified: '2022-06-08T16:39:16.275890+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29689
  title: སྨན་གྱི་རྒྱུད་བཞིའི་བརྡ་དང་དོན་འགའ་ཞིག་དཀྲོལ་བ་རྣམ་རྒྱལ་ཨ་རུ་རའི་འཕྲེང་བའི་མཛེས་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4988':
      image_group_id: I5609
      title: ''
      total_pages: 588
      order: 1
      base_file: 4988.txt
    4E9A:
      image_group_id: I5610
      title: ''
      total_pages: 564
      order: 2
      base_file: 4E9A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
