id: IF089CA46
legacy_id: P010665
ocr_import_info:
  bdrc_scan_id: W29689
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T03:55:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:19:43.572693+00:00'
last_modified: 2022-09-02 22:21:38.510952
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29689
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29689
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྨན་གྱི་རྒྱུད་བཞིའི་བརྡ་དང་དོན་འགའ་ཞིག་དཀྲོལ་བ་རྣམ་རྒྱལ་ཨ་རུ་རའི་འཕྲེང་བའི་མཛེས་རྒྱན།
  author: ལུང་རིགས་བསྟན་དར།
statistics:
  ocr_word_mean_confidence_index: 0.5661926411284626
  ocr_word_median_confidence_index: 0.5699999928474426
quality: null
bases:
  I5609:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5609
      total_pages: 588
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5609.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5590344363924578
    legacy_id: v001
  I5610:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5610
      total_pages: 564
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5610.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5750802548650757
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
